version: 0.0
os: linux
files:
  - source: target/my-app.war
    destination: /opt/apache-tomcat-8.5.47/webapps
permissions:
  - object: /opt/apache-tomcat-8.5.47/webapps/my-app
    group: ec2-user
    mode: 755
    type:
      - directory
hooks:
  BeforeInstall:
    - location: scripts/stopserver.sh
  AfterInstall:
    - location: scripts/startserver.sh
      timeout: 180
  ApplicationStart:
  ValidateService:
