version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - echo $(ls target)
      - echo Build completed on `date`
artifacts:
  files:
    - target/my-app.war
    - scripts/*.sh
    - appspec.yml